CREATE TABLE CUSTOMER_MANAGEMENT(
    CUSTOMER_ID int PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE int(10),
    EMAIL VARCHAR(100) UNIQUE
    
    );