CREATE TABALE TRANSACTIONS(
TRANSACTION_ID int PRIMARY KEY,
ACCOUNT_ID int NOT NULL,
TRANSACTION_DATE DATE NOT NULL,
TRANSACTION_TYPE VARCHAR(50) NOT NULL,
AMOUNT DECIMAL(10,2) NOT NULL,

FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_MANAGEMENT(ACCOUNT_ID)

)