CREATE TABLE ACCOUNT_MANAGEMENT(
    ACCOUNT_ID int PRIMARY KEY,
    CUSTOMER_ID int NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    BALANCE DECIMAL(56,02) NOT NULL,
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_MANAGEMENT(CUSTOMER_ID)
    );